export const ROUTES = {
    PRODUCTS: {
        BASE: 'products',
        CREATE: '',
        GET_ALL: '',
        SEARCH: 'search',
        GET_BY_CATEGORY: 'category/:name',
        GET_ONE: ':id',
        DELETE: ':id',
        UPDATE: ':id'
    },
    CATEGORIES: {
        BASE: 'categories',
        CREATE: '',
        GET_ALL: '',
        GET_ONE: ':id',
        DELETE: ':id',
        UPDATE: ':id'
    },
    BRANDS: {
        BASE: 'brands',
        CREATE: '',
        GET_ALL: '',
        GET_ONE: ':id',
        DELETE: ':id',
        UPDATE: ':id'
    },
    CUSTOMERS: {
        BASE: 'customers',
        CREATE: '',
        GET_ALL: '',
        SEARCH: 'search',
        GET_ONE: ':id',
        UPDATE: ':id',
        DELETE: ':id',
    },
    USERS: {
        BASE: 'users',
        CREATE: '',
        GET_ALL: '',
        SEARCH: 'search',
        GET_BY_ROLE: 'role/:role',
        GET_ONE: ':id',
        UPDATE: ':id',
        DELETE: ':id',
    },
    ORDERS: {
        BASE: 'orders',
        CREATE: '',
        GET_ALL: '',
        SEARCH: 'search',
        GET_BY_STATUS: 'status/:status',
        GET_BY_CUSTOMER: 'customer/:id',
        GET_BY_PRODUCT: 'product/:id',
        GET_ONE: ':id',
        UPDATE: ':id',
        DELETE: ':id',
        GET_TOTAL_PRICE: ':id/total',
    },
    AUTH: {
        BASE: 'auth',
        LOGIN: 'login',
        REGISTER: 'register',
        LOGOUT: 'logout',
        REFRESH: 'refresh',
        FORGOT_PASSWORD: 'forgot-password',
        RESET_PASSWORD: 'reset-password',
        VERIFY_EMAIL: 'verify-email',
    },
    PROFILE: {
        BASE: 'profile',
        ORDERS: 'orders',
        FAVORITES: 'favorites',
        CART: 'cart',
        SETTINGS: 'settings',
    }
};
